2.3 EJERCICIO MODULO 3 PANDAS

# Ejercicios

A lo largo de todos los ejercicios de la clase invertida trabajaremos con un *csv* que contiene información de las ventas de un *e-commerce*. En concreto usaremos un DataFrame que se llama `rating-and-performance.csv`. Nos proporciona información detalladas de las características de cada producto, calificaciones, ventas, reseñas y otras métricas para que podamos comprender qué hace que un producto de verano tenga éxito en Wish. Veamos en detalles sus columnas para entender mejor el conjuntos de datos: 


| Columna                      | Descripción                                                                                                    |
|------------------------------|----------------------------------------------------------------------------------------------------------------|
| title                        | El título del producto. (*object*)                                                                      |
| title_orig                   | El título original del producto. (*object*)                                                             |
| price                        | El precio del producto. (*float*)                                                                             |
| retail_price                 | El precio minorista original del producto. (*float*)                                                           |
| currency_buyer               | La moneda del comprador. (*object*)                                                                     |
| units_sold                   | El número de unidades vendidas. (*integer*)                                                                       |
| uses_ad_boosts               | Un indicador de si el producto ha sido promovido mediante anuncios. (*bool*)                                  |
| rating                       | La calificación del producto. (*float*)                                                                       |
| rating_count                 | El número total de calificaciones para el producto. (*integer*)                                                    |
| rating_five_count            | El número de calificaciones de cinco estrellas para el producto. (*integer*)                                       |
| rating_four_count            | El número de calificaciones de cuatro estrellas para el producto. (*integer*)                                      |
| rating_three_count           | El número de calificaciones de tres estrellas para el producto. (*integer*)                                        |
| rating_two_count             | El número de calificaciones de dos estrellas para el producto. (*integer*)                                         |
| rating_one_count             | El número de calificaciones de una estrella para el producto. (*integer*)                                          |
| badges_count                 | El número de insignias asociadas al producto. (*integer*)                                                          |
| badge_local_product          | Un indicador de si el producto es local. (*bool*)                                                             |
| badge_product_quality        | Un indicador de si el producto tiene una insignia de calidad. (*bool*)                                        |
| badge_fast_shipping          | Un indicador de si el producto tiene una insignia de envío rápido. (*bool*)                                   |
| tags                         | Las etiquetas asociadas al producto. (*object*)                                                         |
| product_color                | El color del producto. (*object*)                                                                       |
| product_variation_inventory  | El inventario de la variación del producto. (*integer*)                                                           |
| shipping_option_name         | El nombre de la opción de envío. (*object*)                                                             |
| shipping_option_price        | El precio de la opción de envío. (*float*)                                                                    |
| shipping_is_express          | Un indicador de si la opción de envío es express. (*bool*)                                                    |
| countries_shipped_to         | Los países a los que se envía el producto. (*object*)                                                   |
| inventory_total              | El inventario total del producto. (*integer*)                                                                     |
| has_urgency_banner           | Un indicador de si el producto tiene un banner de urgencia. (*bool*)                                          |
| urgency_text                 | El texto del banner de urgencia. (*object*)                                                             |
| origin_country               | El país de origen del producto. (*object*)                                                              |
| merchant_title               | El título del comerciante. (*object*)                                                                   |
| merchant_name                | El nombre del comerciante. (*object*)                                                                   |
| merchant_info_subtitle       | El subtítulo del comerciante. (*object*)                                                                |
| merchant_rating_count        | El número total de calificaciones para el comerciante. (*integer*)                                                 |
| merchant_has_profile_picture | Un indicador de si el comerciante tiene una imagen de perfil. (*bool*)                                       |
| merchant_profile_picture     | La imagen de perfil del comerciante. (*object*)                                                         |
| product_url                  | La URL del producto. (*object*)                                                                         |
| product_picture              | La imagen del producto. (*object*)                                                                      |
| theme                        | El tema del producto. (*object*)                                                                        |
| crawl_month                  | El mes en que se obtuvo el producto. (*object*)                                                         |


Para seguir prácticando con Pandas os planteamos los siguientes ejercicios: 

1- Abre el fichero de `rating-and-performance` con el método que sea más correcto. Además muestra las 5 primeras filas del *DataFrame*. 

2- Pongamos en práctica el `loc` e `iloc`:

  - Usando el `loc`: 

      - Extraed todas las filas de la columna "price". ¿De qué tipo es el resultado obtenido?

      - Extraed todas las filas de las columnas "price" y "retail_price". ¿De qué tipo es el resultado obtenido?

      - Extraed las filas pares, de las columnas "rating", "rating_count", "rating_five_count", "rating_four_count", "rating_three_count", "rating_two_count", "rating_one_count". 

    - Extraed las las filas cuyo precio sea mayor que 10 y sus unidades vendidas ("units_sold") sea mayor que 5000. 

  - Usando el `iloc` (sacaremos los mismos resultados que con el loc): 

    - Extraed todas las filas de la columna "price". 

    - Extraed todas las filas de las columnas "price" y "retail_price". 

    - Extraed las filas pares, de las columnas "rating", "rating_count", "rating_five_count", "rating_four_count", "rating_three_count", "rating_two_count", "rating_one_count".

In [18]:
# importando librerias
import pandas as pd

1- Abre el fichero de `rating-and-performance` con el método que sea más correcto. Además muestra las 5 primeras filas del *DataFrame*.

In [19]:
# Paso 1: Abrir el archivo y mostrar las 5 primeras filas del DataFrame
df = pd.read_csv('rating-and-performance.csv')

# Eliminar la primera columna
df = df.iloc[:, 1:]
print("Primeras 5 filas del DataFrame:")
df.head()

Primeras 5 filas del DataFrame:

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
0,2020 Summer Vintage Flamingo Print Pajamas Se...,2020 Summer Vintage Flamingo Print Pajamas Se...,16.00,14,EUR,100,0,3.76,54,26.0,...,568,4.128521,595097d6a26f6e070cb878d1,0,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08
1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,Women's Casual Summer Sleeveless Sexy Mini Dress,8.00,22,EUR,20000,1,3.45,6135,2269.0,...,17752,3.899673,56458aa03a698c35c9050988,0,NaN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,https://contestimg.wish.com/api/webimage/58940...,58940d436a0d3d5da4e95a38,summer,2020-08
2,2020 Nouvelle Arrivée Femmes Printemps et Été ...,2020 New Arrival Women Spring and Summer Beach...,8.00,43,EUR,100,0,3.57,14,5.0,...,295,3.989831,5d464a1ffdf7bc44ee933c65,0,NaN,https://www.wish.com/c/5ea10e2c617580260d55310a,https://contestimg.wish.com/api/webimage/5ea10...,5ea10e2c617580260d55310a,summer,2020-08
3,Hot Summer Cool T-shirt pour les femmes Mode T...,Hot Summer Cool T Shirt for Women Fashion Tops...,8.00,8,EUR,5000,1,4.03,579,295.0,...,23832,4.020435,58cfdefdacb37b556efdff7c,0,NaN,https://www.wish.com/c/5cedf17ad1d44c52c59e4aca,https://contestimg.wish.com/api/webimage/5cedf...,5cedf17ad1d44c52c59e4aca,summer,2020-08
4,Femmes Shorts d'été à lacets taille élastique ...,Women Summer Shorts Lace Up Elastic Waistband ...,2.72,3,EUR,100,1,3.10,20,6.0,...,14482,4.001588,5ab3b592c3911a095ad5dadb,0,NaN,https://www.wish.com/c/5ebf5819ebac372b070b0e70,https://contestimg.wish.com/api/webimage/5ebf5...,5ebf5819ebac372b070b0e70,summer,2020-08

2- Pongamos en práctica el `loc` e `iloc`:

In [20]:
# Paso 2: Usando loc e iloc

# Usando loc:

# Extraer todas las filas de la columna "price"
prices_loc = df.loc[:, 'price']
print("\ndatos de las filas de 'price' usando loc:\n", prices_loc)
print("\nTipo de datos de la columna 'price' usando loc:", prices_loc.dtype)

datos de las filas de 'price' usando loc:
 0       16.00
1        8.00
2        8.00
3        8.00
4        2.72
        ...
1568     6.00
1569     2.00
1570     5.00
1571    13.00
1572     7.00
Name: price, Length: 1573, dtype: float64

Tipo de datos de la columna 'price' usando loc: float64

In [21]:
# Extraer todas las filas de las columnas "price" y "retail_price"
prices_retail_loc = df.loc[:, ['price', 'retail_price']]
print("\ndatos de las filas de 'price' y 'retail_price' usando loc:\n", prices_retail_loc)
print("-----------------------------------------------------------")
print("\nTipo de datos de la columna 'price' y 'retail_price'usando loc:", prices_retail_loc.info())

datos de las filas de 'price' y 'retail_price' usando loc:
       price  retail_price
0     16.00            14
1      8.00            22
2      8.00            43
3      8.00             8
4      2.72             3
...     ...           ...
1568   6.00             9
1569   2.00            56
1570   5.00            19
1571  13.00            11
1572   7.00             6

[1573 rows x 2 columns]
-----------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1573 entries, 0 to 1572
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         1573 non-null   float64
 1   retail_price  1573 non-null   int64
dtypes: float64(1), int64(1)
memory usage: 24.7 KB

Tipo de datos de la columna 'price' y 'retail_price'usando loc: None

In [22]:
# Extraer las filas pares de las columnas especificadas
filas_pares_loc = df.loc[::2, ['rating', 'rating_count', 'rating_five_count', 'rating_four_count', 'rating_three_count', 'rating_two_count', 'rating_one_count']]
filas_pares_loc.head()

,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count
0,3.76,54,26.0,8.0,10.0,1.0,9.0
2,3.57,14,5.0,4.0,2.0,0.0,3.0
4,3.10,20,6.0,4.0,2.0,2.0,6.0
6,3.84,6742,3172.0,1352.0,971.0,490.0,757.0
8,3.47,15,6.0,2.0,3.0,1.0,3.0

In [23]:
# Extraer las filas cuyo precio sea mayor que 10 y sus unidades vendidas sea mayor que 5000
filtro_df_loc = df.loc[(df['price'] > 10) & (df['units_sold'] > 5000)]
filtro_df_loc.head()

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
16,Nouvelle mode d'été pour femmes Robe sans manc...,New Summer Women's Fashion Sleeveless Polka Do...,11.0,10,EUR,10000,0,3.72,2058,840.0,...,6302,3.958426,5b8beef49996c87b299cdbec,0,NaN,https://www.wish.com/c/5cd3e795ebe403118bbc0f89,https://contestimg.wish.com/api/webimage/5cd3e...,5cd3e795ebe403118bbc0f89,summer,2020-08
77,Nouveau Mode Femmes Casual Shorts Costume Été ...,New Fashion Women Casual Shorts Suit Summer Ti...,11.0,10,EUR,10000,0,4.24,1045,644.0,...,9200,4.289674,583e7f658108913bced6f8cf,0,NaN,https://www.wish.com/c/5b29e5b5080ea2661b2287f6,https://contestimg.wish.com/api/webimage/5b29e...,5b29e5b5080ea2661b2287f6,summer,2020-08
89,NOUVELLE Robe d'été sans manches imprimée à fl...,NEW Women Summer Floral Printed Sleeveless Dr...,11.0,10,EUR,20000,1,4.07,3070,1635.0,...,12974,3.965701,5a7b23a69bda4e3d375e7b3f,0,NaN,https://www.wish.com/c/5cf5e44b3c8b9e101a5db52c,https://contestimg.wish.com/api/webimage/5cf5e...,5cf5e44b3c8b9e101a5db52c,summer,2020-08
109,Casual femmes ras du cou à manches courtes feu...,Casual Women Crew Neck Short Sleeve Leaf Print...,11.0,10,EUR,10000,0,3.77,1694,725.0,...,13946,4.000143,559d33adc605853731afbf10,0,NaN,https://www.wish.com/c/5c78151c27202a28a75752b7,https://contestimg.wish.com/api/webimage/5c781...,5c78151c27202a28a75752b7,summer,2020-08
111,Femmes classiques dos nu en dentelle évider li...,Classic Women Backless Lace Hollow Out Halter ...,14.0,12,EUR,10000,0,3.93,2946,1427.0,...,32858,3.885538,57baf75f63834218e305e4f4,0,NaN,https://www.wish.com/c/5acb7ae3a69e662bb0133546,https://contestimg.wish.com/api/webimage/5acb7...,5acb7ae3a69e662bb0133546,summer,2020-08

In [24]:
# Usando iloc (los mismos resultados que con loc):

# Extraer todas las filas de la columna "price"
prices_iloc = df.iloc[:, 2]
prices_iloc

0       16.00
1        8.00
2        8.00
3        8.00
4        2.72
        ...
1568     6.00
1569     2.00
1570     5.00
1571    13.00
1572     7.00
Name: price, Length: 1573, dtype: float64

In [25]:
# Extraer todas las filas de las columnas "price" y "retail_price"
prices_retail_iloc = df.iloc[:, [2, 3]]
prices_retail_iloc

      price  retail_price
0     16.00            14
1      8.00            22
2      8.00            43
3      8.00             8
4      2.72             3
...     ...           ...
1568   6.00             9
1569   2.00            56
1570   5.00            19
1571  13.00            11
1572   7.00             6

[1573 rows x 2 columns]

In [26]:
# Extraer las filas pares de las columnas especificadas
filas_pares_iloc = df.iloc[::2, 7:14]
filas_pares_iloc.head()

,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count
0,3.76,54,26.0,8.0,10.0,1.0,9.0
2,3.57,14,5.0,4.0,2.0,0.0,3.0
4,3.10,20,6.0,4.0,2.0,2.0,6.0
6,3.84,6742,3172.0,1352.0,971.0,490.0,757.0
8,3.47,15,6.0,2.0,3.0,1.0,3.0