- Métodos de unión: (uso práctico)

    - concat() -> lo vamos a usar para poner un df encima del otro (axis = 0)
        - "lo podemos entender como UNION en SQL"
        - las columnas se tienen que llamar igual para que aplile los datos
        - idnore_index = True para que genere un nuevo índice consecutivo y no use los valores originales

    - join / merge -> unen los df uno al lado del otro por el valor de columna/índice

        - join -> usamos los índices de los df. Índice 0 de df1 lo une con índice 0 de df2
            - por defecto hace un LEFT JOIN

        - merge -> igual que el join, pero usamos columnas columnas cómo unión -> fila id del df1 = "MCX" lo une con fila id del df2 = "MCX"
            - por defecto hace INNER JOIN

        - tipos de unión: "inner", "left", "right", "outer" -> dependiendo del tipo de unión nos puede generar valores nulos

In [1]:
import pandas as pd

In [6]:
df1 = pd.DataFrame({"A" :[1,2,3], "B":[4,5,6]})
df2 = pd.DataFrame({"A" :[7,8,9], "B":[10,11,12]}, index=[0,1,3])

In [7]:
df1

   A  B
0  1  4
1  2  5
2  3  6

In [8]:
df2

   A   B
0  7  10
1  8  11
3  9  12

In [10]:
pd.concat([df1, df2], axis = 0, ignore_index=True)

   A   B
0  1   4
1  2   5
2  3   6
3  7  10
4  8  11
5  9  12

In [11]:
pd.concat([df1, df2], axis = 1)

     A    B    A     B
0  1.0  4.0  7.0  10.0
1  2.0  5.0  8.0  11.0
2  3.0  6.0  NaN   NaN
3  NaN  NaN  9.0  12.0

In [12]:
df = pd.read_csv("../files/rating-and-performance.csv", index_col=0)
df.head()

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
index,,,,,,,,,,,,,,,,,,,,,
0,2020 Summer Vintage Flamingo Print Pajamas Se...,2020 Summer Vintage Flamingo Print Pajamas Se...,16.00,14,EUR,100,0,3.76,54,26.0,...,568,4.128521,595097d6a26f6e070cb878d1,0,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08
1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,Women's Casual Summer Sleeveless Sexy Mini Dress,8.00,22,EUR,20000,1,3.45,6135,2269.0,...,17752,3.899673,56458aa03a698c35c9050988,0,NaN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,https://contestimg.wish.com/api/webimage/58940...,58940d436a0d3d5da4e95a38,summer,2020-08
2,2020 Nouvelle Arrivée Femmes Printemps et Été ...,2020 New Arrival Women Spring and Summer Beach...,8.00,43,EUR,100,0,3.57,14,5.0,...,295,3.989831,5d464a1ffdf7bc44ee933c65,0,NaN,https://www.wish.com/c/5ea10e2c617580260d55310a,https://contestimg.wish.com/api/webimage/5ea10...,5ea10e2c617580260d55310a,summer,2020-08
3,Hot Summer Cool T-shirt pour les femmes Mode T...,Hot Summer Cool T Shirt for Women Fashion Tops...,8.00,8,EUR,5000,1,4.03,579,295.0,...,23832,4.020435,58cfdefdacb37b556efdff7c,0,NaN,https://www.wish.com/c/5cedf17ad1d44c52c59e4aca,https://contestimg.wish.com/api/webimage/5cedf...,5cedf17ad1d44c52c59e4aca,summer,2020-08
4,Femmes Shorts d'été à lacets taille élastique ...,Women Summer Shorts Lace Up Elastic Waistband ...,2.72,3,EUR,100,1,3.10,20,6.0,...,14482,4.001588,5ab3b592c3911a095ad5dadb,0,NaN,https://www.wish.com/c/5ebf5819ebac372b070b0e70,https://contestimg.wish.com/api/webimage/5ebf5...,5ebf5819ebac372b070b0e70,summer,2020-08

In [13]:
df_cat = df.select_dtypes(include="O")
df_cat.head()

,title,title_orig,currency_buyer,tags,product_color,product_variation_size_id,shipping_option_name,urgency_text,origin_country,merchant_title,merchant_name,merchant_info_subtitle,merchant_id,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
index,,,,,,,,,,,,,,,,,,,
0,2020 Summer Vintage Flamingo Print Pajamas Se...,2020 Summer Vintage Flamingo Print Pajamas Se...,EUR,"Summer,Fashion,womenunderwearsuit,printedpajam...",white,M,Livraison standard,Quantité limitée !,CN,zgrdejia,zgrdejia,(568 notes),595097d6a26f6e070cb878d1,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08
1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,Women's Casual Summer Sleeveless Sexy Mini Dress,EUR,"Mini,womens dresses,Summer,Patchwork,fashion d...",green,XS,Livraison standard,Quantité limitée !,CN,SaraHouse,sarahouse,"83 % avis positifs (17,752 notes)",56458aa03a698c35c9050988,NaN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,https://contestimg.wish.com/api/webimage/58940...,58940d436a0d3d5da4e95a38,summer,2020-08
2,2020 Nouvelle Arrivée Femmes Printemps et Été ...,2020 New Arrival Women Spring and Summer Beach...,EUR,"Summer,cardigan,women beachwear,chiffon,Sexy w...",leopardprint,XS,Livraison standard,Quantité limitée !,CN,hxt520,hxt520,86 % avis positifs (295 notes),5d464a1ffdf7bc44ee933c65,NaN,https://www.wish.com/c/5ea10e2c617580260d55310a,https://contestimg.wish.com/api/webimage/5ea10...,5ea10e2c617580260d55310a,summer,2020-08
3,Hot Summer Cool T-shirt pour les femmes Mode T...,Hot Summer Cool T Shirt for Women Fashion Tops...,EUR,"Summer,Shorts,Cotton,Cotton T Shirt,Sleeve,pri...",black,M,Livraison standard,NaN,CN,allenfan,allenfan,"(23,832 notes)",58cfdefdacb37b556efdff7c,NaN,https://www.wish.com/c/5cedf17ad1d44c52c59e4aca,https://contestimg.wish.com/api/webimage/5cedf...,5cedf17ad1d44c52c59e4aca,summer,2020-08
4,Femmes Shorts d'été à lacets taille élastique ...,Women Summer Shorts Lace Up Elastic Waistband ...,EUR,"Summer,Plus Size,Lace,Casual pants,Bottom,pant...",yellow,S,Livraison standard,Quantité limitée !,CN,youngpeopleshop,happyhorses,"85 % avis positifs (14,482 notes)",5ab3b592c3911a095ad5dadb,NaN,https://www.wish.com/c/5ebf5819ebac372b070b0e70,https://contestimg.wish.com/api/webimage/5ebf5...,5ebf5819ebac372b070b0e70,summer,2020-08

In [14]:
df_num = df.select_dtypes(exclude="O")
df_num.head()

,price,retail_price,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,...,badge_fast_shipping,product_variation_inventory,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,has_urgency_banner,merchant_rating_count,merchant_rating,merchant_has_profile_picture
index,,,,,,,,,,,,,,,,,,,,,
0,16.00,14,100,0,3.76,54,26.0,8.0,10.0,1.0,...,0,50,4,0,34,50,1.0,568,4.128521,0
1,8.00,22,20000,1,3.45,6135,2269.0,1027.0,1118.0,644.0,...,0,50,2,0,41,50,1.0,17752,3.899673,0
2,8.00,43,100,0,3.57,14,5.0,4.0,2.0,0.0,...,0,1,3,0,36,50,1.0,295,3.989831,0
3,8.00,8,5000,1,4.03,579,295.0,119.0,87.0,42.0,...,0,50,2,0,41,50,NaN,23832,4.020435,0
4,2.72,3,100,1,3.10,20,6.0,4.0,2.0,2.0,...,0,1,1,0,35,50,1.0,14482,4.001588,0

In [16]:
df.describe(include="O").T

,count,unique,top,freq
title,1573,1201,Nouvelle mode d'été femmes robe décontractée c...,24
title_orig,1573,1203,New Fashion Summer Women Casual Dress Round Ne...,24
currency_buyer,1573,1,EUR,1573
tags,1573,1230,"Summer,Fashion,Necks,Skirts,Dress,Loose,Women'...",17
product_color,1532,101,black,302
product_variation_size_id,1559,106,S,641
shipping_option_name,1573,15,Livraison standard,1508
urgency_text,473,2,Quantité limitée !,472
origin_country,1556,6,CN,1516
merchant_title,1573,958,guangzhouweishiweifushiyouxiangongsi,15
merchant_name,1569,957,广州唯适唯服饰有限公司,15
merchant_info_subtitle,1572,1058,"83 % avis positifs (32,168 notes)",14
merchant_id,1573,958,558c2cdc89d53c4005ea2920,15
merchant_profile_picture,226,125,https://s3-us-west-1.amazonaws.com/sweeper-pro...,12
product_url,1573,1341,https://www.wish.com/c/5e16cb87e6dd7c03be24b28a,3
product_picture,1573,1341,https://contestimg.wish.com/api/webimage/5e16c...,3
product_id,1573,1341,5e16cb87e6dd7c03be24b28a,3
theme,1573,1,summer,1573
crawl_month,1573,1,2020-08,1573

In [17]:
df.shape

(1573, 43)

In [18]:
df_cat.shape

(1573, 19)

In [19]:
df_num.shape

(1573, 24)

In [20]:
df_unido = pd.concat([df_cat, df_num], axis = 1)

df_unido.shape

(1573, 43)

In [21]:
df_unido_2 = df_cat.join(df_num)

In [22]:
df_unido_2.shape

(1573, 43)

In [23]:
df_cat.head()

,title,title_orig,currency_buyer,tags,product_color,product_variation_size_id,shipping_option_name,urgency_text,origin_country,merchant_title,merchant_name,merchant_info_subtitle,merchant_id,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
index,,,,,,,,,,,,,,,,,,,
0,2020 Summer Vintage Flamingo Print Pajamas Se...,2020 Summer Vintage Flamingo Print Pajamas Se...,EUR,"Summer,Fashion,womenunderwearsuit,printedpajam...",white,M,Livraison standard,Quantité limitée !,CN,zgrdejia,zgrdejia,(568 notes),595097d6a26f6e070cb878d1,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08
1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,Women's Casual Summer Sleeveless Sexy Mini Dress,EUR,"Mini,womens dresses,Summer,Patchwork,fashion d...",green,XS,Livraison standard,Quantité limitée !,CN,SaraHouse,sarahouse,"83 % avis positifs (17,752 notes)",56458aa03a698c35c9050988,NaN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,https://contestimg.wish.com/api/webimage/58940...,58940d436a0d3d5da4e95a38,summer,2020-08
2,2020 Nouvelle Arrivée Femmes Printemps et Été ...,2020 New Arrival Women Spring and Summer Beach...,EUR,"Summer,cardigan,women beachwear,chiffon,Sexy w...",leopardprint,XS,Livraison standard,Quantité limitée !,CN,hxt520,hxt520,86 % avis positifs (295 notes),5d464a1ffdf7bc44ee933c65,NaN,https://www.wish.com/c/5ea10e2c617580260d55310a,https://contestimg.wish.com/api/webimage/5ea10...,5ea10e2c617580260d55310a,summer,2020-08
3,Hot Summer Cool T-shirt pour les femmes Mode T...,Hot Summer Cool T Shirt for Women Fashion Tops...,EUR,"Summer,Shorts,Cotton,Cotton T Shirt,Sleeve,pri...",black,M,Livraison standard,NaN,CN,allenfan,allenfan,"(23,832 notes)",58cfdefdacb37b556efdff7c,NaN,https://www.wish.com/c/5cedf17ad1d44c52c59e4aca,https://contestimg.wish.com/api/webimage/5cedf...,5cedf17ad1d44c52c59e4aca,summer,2020-08
4,Femmes Shorts d'été à lacets taille élastique ...,Women Summer Shorts Lace Up Elastic Waistband ...,EUR,"Summer,Plus Size,Lace,Casual pants,Bottom,pant...",yellow,S,Livraison standard,Quantité limitée !,CN,youngpeopleshop,happyhorses,"85 % avis positifs (14,482 notes)",5ab3b592c3911a095ad5dadb,NaN,https://www.wish.com/c/5ebf5819ebac372b070b0e70,https://contestimg.wish.com/api/webimage/5ebf5...,5ebf5819ebac372b070b0e70,summer,2020-08

In [24]:
df_num.head()

,price,retail_price,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,...,badge_fast_shipping,product_variation_inventory,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,has_urgency_banner,merchant_rating_count,merchant_rating,merchant_has_profile_picture
index,,,,,,,,,,,,,,,,,,,,,
0,16.00,14,100,0,3.76,54,26.0,8.0,10.0,1.0,...,0,50,4,0,34,50,1.0,568,4.128521,0
1,8.00,22,20000,1,3.45,6135,2269.0,1027.0,1118.0,644.0,...,0,50,2,0,41,50,1.0,17752,3.899673,0
2,8.00,43,100,0,3.57,14,5.0,4.0,2.0,0.0,...,0,1,3,0,36,50,1.0,295,3.989831,0
3,8.00,8,5000,1,4.03,579,295.0,119.0,87.0,42.0,...,0,50,2,0,41,50,NaN,23832,4.020435,0
4,2.72,3,100,1,3.10,20,6.0,4.0,2.0,2.0,...,0,1,1,0,35,50,1.0,14482,4.001588,0

In [26]:
df_num.reset_index(drop=False, inplace=True)

In [27]:
df_num.head()

,index,price,retail_price,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,...,badge_fast_shipping,product_variation_inventory,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,has_urgency_banner,merchant_rating_count,merchant_rating,merchant_has_profile_picture
0,0,16.00,14,100,0,3.76,54,26.0,8.0,10.0,...,0,50,4,0,34,50,1.0,568,4.128521,0
1,1,8.00,22,20000,1,3.45,6135,2269.0,1027.0,1118.0,...,0,50,2,0,41,50,1.0,17752,3.899673,0
2,2,8.00,43,100,0,3.57,14,5.0,4.0,2.0,...,0,1,3,0,36,50,1.0,295,3.989831,0
3,3,8.00,8,5000,1,4.03,579,295.0,119.0,87.0,...,0,50,2,0,41,50,NaN,23832,4.020435,0
4,4,2.72,3,100,1,3.10,20,6.0,4.0,2.0,...,0,1,1,0,35,50,1.0,14482,4.001588,0

In [30]:
df_num2 = df_num.drop([0,1,2,3,4], axis = 0).reset_index()

In [32]:
df_num2.set_index("index")

,level_0,price,retail_price,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,...,badge_fast_shipping,product_variation_inventory,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,has_urgency_banner,merchant_rating_count,merchant_rating,merchant_has_profile_picture
index,,,,,,,,,,,,,,,,,,,,,
5,5,3.92,9,10,0,5.00,1,1.0,0.0,0.0,...,0,1,1,0,40,50,NaN,65,3.507692,0
6,6,7.00,6,50000,0,3.84,6742,3172.0,1352.0,971.0,...,0,50,2,0,31,50,NaN,10194,4.076516,1
7,7,12.00,11,1000,0,3.76,286,120.0,56.0,61.0,...,0,50,3,0,139,50,NaN,342,3.681287,0
8,8,11.00,84,100,1,3.47,15,6.0,2.0,3.0,...,0,50,2,0,36,50,1.0,330,3.803030,0
9,9,5.78,22,5000,0,3.60,687,287.0,128.0,92.0,...,0,50,2,0,33,50,NaN,5534,3.999819,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1568,1568,6.00,9,10000,1,4.08,1367,722.0,293.0,185.0,...,0,50,2,0,41,50,NaN,5316,4.224605,0
1569,1569,2.00,56,100,1,3.07,28,11.0,3.0,1.0,...,0,2,1,0,26,50,1.0,4435,3.696054,0
1570,1570,5.00,19,100,0,3.71,59,24.0,15.0,8.0,...,0,15,2,0,11,50,NaN,210,3.961905,0
1571,1571,13.00,11,100,0,2.50,2,0.0,1.0,0.0,...,0,36,3,0,29,50,NaN,31,3.774194,0
1572,1572,7.00,6,100,1,4.07,14,8.0,3.0,1.0,...,0,50,2,0,41,50,NaN,7023,4.235939,0

In [36]:
df_cat.head(10)

,title,title_orig,currency_buyer,tags,product_color,product_variation_size_id,shipping_option_name,urgency_text,origin_country,merchant_title,merchant_name,merchant_info_subtitle,merchant_id,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
index,,,,,,,,,,,,,,,,,,,
0,2020 Summer Vintage Flamingo Print Pajamas Se...,2020 Summer Vintage Flamingo Print Pajamas Se...,EUR,"Summer,Fashion,womenunderwearsuit,printedpajam...",white,M,Livraison standard,Quantité limitée !,CN,zgrdejia,zgrdejia,(568 notes),595097d6a26f6e070cb878d1,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08
1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,Women's Casual Summer Sleeveless Sexy Mini Dress,EUR,"Mini,womens dresses,Summer,Patchwork,fashion d...",green,XS,Livraison standard,Quantité limitée !,CN,SaraHouse,sarahouse,"83 % avis positifs (17,752 notes)",56458aa03a698c35c9050988,NaN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,https://contestimg.wish.com/api/webimage/58940...,58940d436a0d3d5da4e95a38,summer,2020-08
2,2020 Nouvelle Arrivée Femmes Printemps et Été ...,2020 New Arrival Women Spring and Summer Beach...,EUR,"Summer,cardigan,women beachwear,chiffon,Sexy w...",leopardprint,XS,Livraison standard,Quantité limitée !,CN,hxt520,hxt520,86 % avis positifs (295 notes),5d464a1ffdf7bc44ee933c65,NaN,https://www.wish.com/c/5ea10e2c617580260d55310a,https://contestimg.wish.com/api/webimage/5ea10...,5ea10e2c617580260d55310a,summer,2020-08
3,Hot Summer Cool T-shirt pour les femmes Mode T...,Hot Summer Cool T Shirt for Women Fashion Tops...,EUR,"Summer,Shorts,Cotton,Cotton T Shirt,Sleeve,pri...",black,M,Livraison standard,NaN,CN,allenfan,allenfan,"(23,832 notes)",58cfdefdacb37b556efdff7c,NaN,https://www.wish.com/c/5cedf17ad1d44c52c59e4aca,https://contestimg.wish.com/api/webimage/5cedf...,5cedf17ad1d44c52c59e4aca,summer,2020-08
4,Femmes Shorts d'été à lacets taille élastique ...,Women Summer Shorts Lace Up Elastic Waistband ...,EUR,"Summer,Plus Size,Lace,Casual pants,Bottom,pant...",yellow,S,Livraison standard,Quantité limitée !,CN,youngpeopleshop,happyhorses,"85 % avis positifs (14,482 notes)",5ab3b592c3911a095ad5dadb,NaN,https://www.wish.com/c/5ebf5819ebac372b070b0e70,https://contestimg.wish.com/api/webimage/5ebf5...,5ebf5819ebac372b070b0e70,summer,2020-08
5,Plus la taille d'été femmes décontracté sans m...,Plus Size Summer Women Casual Sleeveless Rompe...,EUR,"Deep V-Neck,Summer,Plus Size,Spaghetti Strap,O...",navyblue,Size-XS,Livraison standard,NaN,CN,zhoulinglinga,zhoulinglinga,75 % avis positifs (65 notes),5e4b9c3801ba9d210036fc5a,NaN,https://www.wish.com/c/5ec645bafd107a02279c8c54,https://contestimg.wish.com/api/webimage/5ec64...,5ec645bafd107a02279c8c54,summer,2020-08
6,Women Fashion Loose Lace Blouse Blouse V Neck ...,Women Fashion Loose Lace Blouse V Neck Bat Sle...,EUR,"blouse,Women,lace t shirt,summer t-shirts,Lace...",white,XS,Livraison standard,NaN,CN,Unique Li Fashion Shop,uniquelifashionshopbb657bfe91d211e598c7063a14d...,"86 % avis positifs (10,194 notes)",5652f4053a698c76dc9a3f37,https://s3-us-west-1.amazonaws.com/sweeper-pro...,https://www.wish.com/c/5c63a337d5e2ce4bbb3152cf,https://contestimg.wish.com/api/webimage/5c63a...,5c63a337d5e2ce4bbb3152cf,summer,2020-08
7,Robe tunique ample femme Robe d'été Robe en je...,Women's Baggy Tunic Dress Summer Dress Denim D...,EUR,"Jeans,Fashion,tunic,Shirt,Summer,Dress,Denim,s...",blue,M.,Livraison standard,NaN,CN,So Band,soband,(342 notes),5d45349676befe65691dcfbb,NaN,https://www.wish.com/c/5e0ae5ebc2efb76ccf0a3391,https://contestimg.wish.com/api/webimage/5e0ae...,5e0ae5ebc2efb76ccf0a3391,summer,2020-08
8,Robe d'été décontractée à manches courtes pour...,Women's Summer Casual Dress Fashion Short Slee...,EUR,"slim dress,summer dress,womenshortsleevedre,Sl...",black,M,Livraison standard,Quantité limitée !,CN,chenxiangjunjun,chenxiangjunjun,82 % avis positifs (330 notes),5d42980e8388970d32294ddc,NaN,https://www.wish.com/c/5e6f1fb7fe4a5bb4b8bf36e5,https://contestimg.wish.com/api/webimage/5e6f1...,5e6f1fb7fe4a5bb4b8bf36e5,summer,2020-08
9,"Femmes d'été, plus la taille décontractée lâch...",Summer Women Plus Size Casual Loose V Neck Sho...,EUR,"blouse,Summer,Plus Size,Floral print,Necks,Sle...",beige,S,Livraison standard,NaN,CN,Luowei clothe,luoweiclothe,"85 % avis positifs (5,534 notes)",5ba2251b4315d12ebce873fa,NaN,https://www.wish.com/c/5ccfaf238a8d535cec2dfb47,https://contestimg.wish.com/api/webimage/5ccfa...,5ccfaf238a8d535cec2dfb47,summer,2020-08

In [33]:
df_num2.join(df_cat, on="level_0", how="outer")

,level_0,index,price,retail_price,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,rating_four_count,...,merchant_title,merchant_name,merchant_info_subtitle,merchant_id,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
0.0,5,5.0,3.92,9.0,10.0,0.0,5.00,1.0,1.0,0.0,...,zhoulinglinga,zhoulinglinga,75 % avis positifs (65 notes),5e4b9c3801ba9d210036fc5a,NaN,https://www.wish.com/c/5ec645bafd107a02279c8c54,https://contestimg.wish.com/api/webimage/5ec64...,5ec645bafd107a02279c8c54,summer,2020-08
1.0,6,6.0,7.00,6.0,50000.0,0.0,3.84,6742.0,3172.0,1352.0,...,Unique Li Fashion Shop,uniquelifashionshopbb657bfe91d211e598c7063a14d...,"86 % avis positifs (10,194 notes)",5652f4053a698c76dc9a3f37,https://s3-us-west-1.amazonaws.com/sweeper-pro...,https://www.wish.com/c/5c63a337d5e2ce4bbb3152cf,https://contestimg.wish.com/api/webimage/5c63a...,5c63a337d5e2ce4bbb3152cf,summer,2020-08
2.0,7,7.0,12.00,11.0,1000.0,0.0,3.76,286.0,120.0,56.0,...,So Band,soband,(342 notes),5d45349676befe65691dcfbb,NaN,https://www.wish.com/c/5e0ae5ebc2efb76ccf0a3391,https://contestimg.wish.com/api/webimage/5e0ae...,5e0ae5ebc2efb76ccf0a3391,summer,2020-08
3.0,8,8.0,11.00,84.0,100.0,1.0,3.47,15.0,6.0,2.0,...,chenxiangjunjun,chenxiangjunjun,82 % avis positifs (330 notes),5d42980e8388970d32294ddc,NaN,https://www.wish.com/c/5e6f1fb7fe4a5bb4b8bf36e5,https://contestimg.wish.com/api/webimage/5e6f1...,5e6f1fb7fe4a5bb4b8bf36e5,summer,2020-08
4.0,9,9.0,5.78,22.0,5000.0,0.0,3.60,687.0,287.0,128.0,...,Luowei clothe,luoweiclothe,"85 % avis positifs (5,534 notes)",5ba2251b4315d12ebce873fa,NaN,https://www.wish.com/c/5ccfaf238a8d535cec2dfb47,https://contestimg.wish.com/api/webimage/5ccfa...,5ccfaf238a8d535cec2dfb47,summer,2020-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,zgrdejia,zgrdejia,(568 notes),595097d6a26f6e070cb878d1,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08
NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,SaraHouse,sarahouse,"83 % avis positifs (17,752 notes)",56458aa03a698c35c9050988,NaN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,https://contestimg.wish.com/api/webimage/58940...,58940d436a0d3d5da4e95a38,summer,2020-08
NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,hxt520,hxt520,86 % avis positifs (295 notes),5d464a1ffdf7bc44ee933c65,NaN,https://www.wish.com/c/5ea10e2c617580260d55310a,https://contestimg.wish.com/api/webimage/5ea10...,5ea10e2c617580260d55310a,summer,2020-08
NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,allenfan,allenfan,"(23,832 notes)",58cfdefdacb37b556efdff7c,NaN,https://www.wish.com/c/5cedf17ad1d44c52c59e4aca,https://contestimg.wish.com/api/webimage/5cedf...,5cedf17ad1d44c52c59e4aca,summer,2020-08
NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,youngpeopleshop,happyhorses,"85 % avis positifs (14,482 notes)",5ab3b592c3911a095ad5dadb,NaN,https://www.wish.com/c/5ebf5819ebac372b070b0e70,https://contestimg.wish.com/api/webimage/5ebf5...,5ebf5819ebac372b070b0e70,summer,2020-08

In [40]:
df1 = pd.DataFrame({"A" :[1,2,3], "B":[4,5,6]})
df2 = pd.DataFrame({"C" :[7,8,9], "D":[10,11,12]}, index=[0,1,3])

In [41]:
df1

   A  B
0  1  4
1  2  5
2  3  6

In [42]:
df2

   C   D
0  7  10
1  8  11
3  9  12

In [43]:
df1.join(df2, how="outer")

     A    B    C     D
0  1.0  4.0  7.0  10.0
1  2.0  5.0  8.0  11.0
2  3.0  6.0  NaN   NaN
3  NaN  NaN  9.0  12.0

In [45]:
df1.join(df2, on="A")

   A  B    C     D
0  1  4  8.0  11.0
1  2  5  NaN   NaN
2  3  6  9.0  12.0

In [54]:
df1 = pd.DataFrame({"id" :[1,2,3], "B":[4,5,6]})
df2 = pd.DataFrame({"id" :[1,2,3], "B":[10,11,12]}, index=[0,1,3])

In [55]:
display(df1)
display(df2)

   id  B
0   1  4
1   2  5
2   3  6

   id   B
0   1  10
1   2  11
3   3  12

In [56]:
df1.merge(df2, on="id")

   id  B_x  B_y
0   1    4   10
1   2    5   11
2   3    6   12

In [57]:
df["merchant_info_subtitle"]

index
0                             (568 notes)
1       83 % avis positifs (17,752 notes)
2          86 % avis positifs (295 notes)
3                          (23,832 notes)
4       85 % avis positifs (14,482 notes)
                      ...
1568     90 % avis positifs (5,316 notes)
1569                        (4,435 notes)
1570       86 % avis positifs (210 notes)
1571        77 % avis positifs (31 notes)
1572     90 % avis positifs (7,023 notes)
Name: merchant_info_subtitle, Length: 1573, dtype: object

In [58]:
x = "86 % avis positifs (10,194 notes)"

In [74]:
x.split("(")

['86 % avis positifs ', '10,194 notes)']

In [61]:
x.split("(")[0].strip()

'86 % avis positifs'

In [69]:
df["merchant_info_subtitle"] = df["merchant_info_subtitle"].str.split("(", expand=True).get(0)

In [71]:
df[["merchant_rating_count",	"merchant_rating", "merchant_info_subtitle"]].head()

       merchant_rating_count  merchant_rating merchant_info_subtitle
index
0                        568         4.128521
1                      17752         3.899673    83 % avis positifs
2                        295         3.989831    86 % avis positifs
3                      23832         4.020435
4                      14482         4.001588    85 % avis positifs

In [75]:
num = "25856,8$"

In [77]:
num.replace(",", ".").replace("$", "")

'25856.8'